# Generated by Django 5.2.17 on 2026-09-22 21:16

import django.db.models.deletion
import django.utils.timezone
import ring.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255, unique=True)),
                (
                    "v4",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4", unique=True
                    ),
                ),
                (
                    "v6",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv6", unique=True
                    ),
                ),
                ("autnum", models.IntegerField()),
                ("country", models.CharField(blank=True, max_length=2, null=True)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("dc", models.CharField(blank=True, max_length=2048, null=True)),
                ("geo", models.CharField(blank=True, max_length=255, null=True)),
                ("tstamp", ring.fields.EpochDateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=None, null=True)),
                ("alive_v4", models.BooleanField(default=None, null=True)),
                ("alive_v6", models.BooleanField(default=None, null=True)),
                ("last_active", ring.fields.EpochDateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "machines",
                "ordering": ["hostname"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, unique=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("contact", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=255)),
                ("nocemail", models.EmailField(blank=True, default="", max_length=255)),
                ("companydesc", models.TextField(blank=True, null=True)),
                ("public", models.BooleanField(default=None, null=True)),
                ("tstamp", ring.fields.EpochDateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "participants",
                "ordering": ["company"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.IntegerField(unique=True)),
                ("autnum", models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnsibleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("unreachable", models.PositiveIntegerField(blank=True, null=True)),
                ("ok", models.PositiveIntegerField(blank=True, null=True)),
                ("changed", models.PositiveIntegerField(blank=True, null=True)),
                ("skipped", models.PositiveIntegerField(blank=True, null=True)),
                ("failures", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ansible",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["hostname", "-timestamp"],
                        name="ansible_hostnam_0e9666_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "family",
                    models.IntegerField(
                        blank=True, choices=[(4, "IPv4"), (6, "IPv6")], null=True
                    ),
                ),
                ("summary", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "health",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["hostname", "-timestamp"],
                        name="health_hostnam_55880d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MachineRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("tstamp", ring.fields.EpochDateTimeField(blank=True, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="remarks",
                        to="ring.machine",
                    ),
                ),
            ],
            options={
                "db_table": "mremarks",
                "ordering": ["-tstamp"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("tstamp", ring.fields.EpochDateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="remarks",
                        to="ring.participant",
                    ),
                ),
            ],
            options={
                "db_table": "premarks",
                "ordering": ["-tstamp"],
            },
        ),
        migrations.CreateModel(
            name="PeeringDBSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peeringdb_id", models.IntegerField(unique=True)),
                ("peeringdb_net_id", models.IntegerField()),
                ("asn", models.IntegerField()),
                ("net_name", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_peeringdb_signups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "django_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peeringdb_signup",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="RingSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.IntegerField()),
                (
                    "ring_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_signups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "django_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ring_signup",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="RingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("userid", models.IntegerField(blank=True, null=True)),
                ("shell", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=None, null=True)),
                ("admin", models.BooleanField(default=None, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="users",
                        to="ring.participant",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["username"],
            },
        ),
        migrations.AddField(
            model_name="machine",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="machines",
                to="ring.ringuser",
            ),
        ),
        migrations.CreateModel(
            name="RingUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ring_user_id", models.IntegerField(unique=True)),
                (
                    "peeringdb_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("peeringdb_net_id", models.IntegerField(blank=True, null=True)),
                (
                    "django_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ring_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSHHostKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keytype", models.CharField(max_length=255)),
                ("sshkey", models.CharField(max_length=16384)),
                ("keyid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hostkeys",
                        to="ring.machine",
                    ),
                ),
            ],
            options={
                "db_table": "sshhostkeys",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keytype", models.CharField(max_length=255)),
                ("sshkey", models.CharField(blank=True, max_length=16384, null=True)),
                ("keyid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sshkeys",
                        to="ring.ringuser",
                    ),
                ),
            ],
            options={
                "db_table": "sshkeys",
                "ordering": ["id"],
            },
        ),
    ]
