# Generated by Django 5.2.17 on 2026-09-22 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="owner",
            field=models.ForeignKey(
                db_column="owner",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="machines",
                to="ring.ringuser",
            ),
        ),
        migrations.AlterField(
            model_name="machineremark",
            name="machine",
            field=models.ForeignKey(
                db_column="machine",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="remarks",
                to="ring.machine",
            ),
        ),
        migrations.AlterField(
            model_name="participantremark",
            name="participant",
            field=models.ForeignKey(
                db_column="participant",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="remarks",
                to="ring.participant",
            ),
        ),
        migrations.AlterField(
            model_name="ringuser",
            name="participant",
            field=models.ForeignKey(
                db_column="participant",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="users",
                to="ring.participant",
            ),
        ),
        migrations.AlterField(
            model_name="sshhostkey",
            name="machine",
            field=models.ForeignKey(
                db_column="machine",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hostkeys",
                to="ring.machine",
            ),
        ),
        migrations.AlterField(
            model_name="sshkey",
            name="user",
            field=models.ForeignKey(
                db_column="user",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sshkeys",
                to="ring.ringuser",
            ),
        ),
    ]
