# Generated by Django 5.2.17 on 2026-09-25 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ring", "0002_alter_machine_owner_alter_machineremark_machine_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeeringDBNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peeringdb_net_id", models.IntegerField()),
                ("asn", models.IntegerField()),
                ("net_name", models.CharField(blank=True, max_length=255, null=True)),
                ("participant_id", models.IntegerField()),
                (
                    "django_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdb_networks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("django_user", "peeringdb_net_id")},
            },
        ),
    ]
