"""Generation of the ring-ansible repository files (hostfile, hostkeyfile,
users file). Faithful ports of ring-admin.py's ansible_generate_* methods.
"""

from ring.models import Machine, RingUser


def hostfile_text():
    """Return the text of the ansible `nodes` (hostfile) inventory file."""
    lines = ["# Generated by ringadmin", "", "[ringnode]"]
    users = RingUser.objects.all()
    for u in users:
        if u.admin == 1:
            continue
        for m in u.machines.all():
            line = "%s OWNER=%s" % (m.hostname, u.username)
            if m.v4:
                line += " V4=%s" % m.v4
            if m.v6:
                line += " V6=%s" % m.v6
            lines.append(line)
    return "\n".join(lines) + "\n"


def hostkeyfile_text():
    """Return the ssh_known_hosts text for ansible's etcfiles role."""
    lines = ["# Generated by ringadmin", ""]
    users = RingUser.objects.all()
    for u in users:
        for m in u.machines.all():
            namestr = m.hostname
            if m.v4:
                namestr += ",%s" % m.v4
            if m.v6:
                namestr += ",%s" % m.v6
            for k in m.hostkeys.all():
                lines.append(
                    "%s %s %s %s" % (namestr, k.keytype, k.sshkey, k.keyid)
                )
    return "\n".join(lines) + "\n"


def userfile_text():
    """Return the ring-users.yml vars file for ansible's users role."""
    lines = ["# Generated by ringadmin", "", "GROUPS:", "  ring-users:", "    gid: 5000", "  admin:", "    gid: 99", "    sudo: true", "", "USERS:", "  ubuntu:", "    state: absent", "  nlnog:", "    state: absent", "  ring:", "    state: absent", ""]
    users = RingUser.objects.filter(admin__isnull=True) | RingUser.objects.exclude(admin=1)
    users = users.distinct().order_by("username")
    for u in users:
        p = u.participant
        lines.append("  %s:" % u.username)
        lines.append("    state: %s" % ("absent" if u.active == 0 else "present"))
        lines.append("    company: '%s'" % p.company)
        if u.email:
            lines.append("    email: '%s'" % u.email)
        else:
            lines.append("    email: '%s'" % p.nocemail)
        lines.append("    uid: %s" % u.userid)
        if u.shell:
            lines.append("    shell: %s" % u.shell)
        lines.append("    groups:")
        lines.append("      - ring-users")
        lines.append("")
    return "\n".join(lines) + "\n"


def machine_hostsfile_line(machine):
    """Hostsfile line for a single machine (legacy cmd_generate_hostsfile)."""
    name = machine.short_hostname
    lines = ["%s  %s %s" % (machine.v6, name, machine.hostname)]
    if machine.v4:
        lines.append("%s    %s %s" % (machine.v4, name, machine.hostname))
    return "\n".join(lines) + "\n"